name: Deploy Documentation Site

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    # - run: npm i yarn -g
    
    - run: yarn && yarn workspace build @axew/jugg && yarn workspace build @axew/jugg-plugin-doc
      
    # https://github.com/JamesIves/github-pages-deploy-action    
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: siteDist
