name: Deploy Documentation Site

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: siteDist
        BUILD_SCRIPT: yarn && yarn workspace @axew/jugg build && yarn workspace @axew/jugg-plugin-doc build && yarn doc:build
