name: Deploy Documentation Site

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Use Node.js # 配置Node环境
      uses: actions/setup-node@v1 # 配置脚本来自 https://github.com/actions/setup-node
      with:
        node-version: "12.x"
    
    - run: yarn install
    
    - run: yarn workspace @axew/jugg build && yarn workspace @axew/jugg-plugin-doc build
    
    - run: yarn install --force
    
    - run: yarn doc:build
      
    # https://github.com/JamesIves/github-pages-deploy-action    
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: siteDist
